routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [\App\Http\Controllers\dashboard\HomeController::class,'index']);
Route::get('datatable', [\App\Http\Controllers\DataTableController::class,'index']); 
Route::get('get', [\App\Http\Controllers\DataTableController::class,'get']);

app/Models/Traits/UserTraits/UserMethod.php
<?php

namespace App\Models\Traits\UserTraits;

/**
 * Trait UserMethod.
 */
trait UserMethod
{
    public function hasRole($role){
        if ($this->role()->where('name',$role)->first()){
            return true;
        }
        return false;
    }

    public function isAdmin()
    {
        return $this->hasRole(config('access.users.admin_role'));
    }
    public function isUser()
    {
        return $this->hasRole(config('access.users.default_role'));
    }
     public function isProvider()
    {
        return $this->hasRole('provider');
    }

    public function isEmployee()
    {
        return $this->hasRole('employee');
    }
    
   

    public static function defaultTip(){
        $default= DB::table('users')
            ->where('name',config('user'))->first();
        return $default->id;
    }
}

app/Http/Controllers/dashboard/CountryController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Country;
use App\Repositories\backend\CountryRepository;
use App\Events\Backend\Country\CountryDeleted;
use Illuminate\Support\Facades\Http;
 

class CountryController extends Controller
{
    public $countryRepository;

    public function __construct(CountryRepository $countryRepository)
    {
        $this->countryRepository = $countryRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries = Country::all();
        return view('dashboard.countries.index', compact('countries'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();
        return view('dashboard.countries.create',compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->countryRepository->create($request->only(
            'name',
            'flag',
            'currency',
            'fees',
        ));
        session()->flash('success', __('Country Created'));
        return redirect()->route('countries.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $country = Country::findOrFail($id);

        //return show view
        return view('dashboard.countries.show', compact('country'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
       //find country
       $country = Country::findOrFail($id);
       //return edit view
       return view('dashboard.countries.edit', compact('country'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //find country
        $country=Country::where('id',$id)->first();
        //update country
        $this->countryRepository->update($country,$request->only(
            'name',
            'flag',
            'currency',
            'fees',   
        ));
        session()->flash('success', __('Country Updated'));
        return redirect()->route('countries.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //find counrty
       $counrty=Country::findOrFail($id);
       //delete counrty
       $counrty->delete();
       //event delete counrty
       event(new CountryDeleted($counrty));
       session()->flash('success', __('Country Deleted'));
       return redirect()->route('countries.index');
    }

    function country() {
        $data =Http::get('https://stg.api.akremapp.com/api/all_countries')->json();
        return view('dashboard.json.country',['data' => $data]);

    }
}

app/Http/Controllers/dashboard/CustomerController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Customer;
use App\Models\Country;
use App\Models\User;
use App\Events\Backend\Customer\CustomerDeleted;
use App\Http\Requests\backend\customer\UpdateCustomerRequest;
use App\Http\Requests\backend\customer\StoreCustomerRequest;
use App\Repositories\backend\CustomerRepository;



class CustomerController extends Controller
{
    public $customerRepository;

    public function __construct(CustomerRepository $customerRepository)
    {
        $this->customerRepository = $customerRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $customers = User::where('role_id',2)->get();
        $customers = Customer::all();
  
        return view('dashboard.customers.index', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function activeCustomer($id){
        $customer=Customer::findOrFail($id);
        // $this->customerRepository->active($customer);
        $customer->is_active=1;
        $customer->save();
        session()->flash('success', __('Customer Activated'));
        return redirect()->route('customers.index');
    }

    public function deactiveCustomer($id){
        $customer=Customer::findOrFail($id);
        $customer->is_active=0;
        $customer->save();
        session()->flash('success', __('Customer Deactivated'));
        return redirect()->route('customers.index');
    }

    public function create()
    {
        $customers = Customer::all();
        return view('dashboard.customers.create',compact('customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEmployeeRequest $request)
    {
        $this->customerRepository->create($request->only(
            'name',
            'email',
            'phone_number',
            'country_id',
        ));
        session()->flash('success', __('Customer Created'));
        return redirect()->route('customers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $customer = Customer::findOrFail($id);
        $customer = Customer::findOrFail($id);

        //return show view
        return view('dashboard.customers.show', compact('customer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $countries = Country::all();

        //find customer
        $customer = Customer::findOrFail($id);
        //return edit view
        return view('dashboard.customers.edit', compact('countries','customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCustomerRequest $request, $id)
    {
       //find customer
       $customer=Customer::where('id',$id)->first();
       //update customer
       $this->customerRepository->update($customer,$request->only(
        'name',
        'email',
        'phone_number',
        'country_id',
       ));
       session()->flash('success', __('Customer Updated'));
       return redirect()->route('customers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       //find customer
       $customer=Customer::findOrFail($id);
       //delete customer
       $customer->delete();
       $user=User::where('email',$customer->email)->first();
       $user->delete();
       //event delete customer
       event(new CustomerDeleted($customer));
       session()->flash('success', __('Customer Deleted'));
       return redirect()->route('customers.index');
    }
}

app/Http/Controllers/dashboard/DepartmentController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Department;
use App\Models\Profile;
use App\Models\User;
use App\Repositories\backend\DepartmentRepository;
use App\Http\Requests\backend\department\UpdateDepartmentRequest;
use App\Http\Requests\backend\department\StoreDepartmentRequest;
use App\Events\Backend\Department\DepartmentDeleted;




class DepartmentController extends Controller
{
    public $departmentRepository;

    public function __construct(DepartmentRepository $departmentRepository)
    {
    
        $this->departmentRepository = $departmentRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user= auth()->user()->id;
        $user = User::findOrFail($user);
        $partner = Profile::where('contact_email',$user->email)->first();
        $departments = Department::where('partner_id',$partner->id)->get();
        return view('dashboard.departments.index', compact('departments'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $partners = Profile::all();
        return view('dashboard.departments.create',compact('partners'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreDepartmentRequest $request)
    {
       
        $this->departmentRepository->create($request->only(
            'name',
            'partner_id',
        ));
        session()->flash('success', __('Department Created'));
        return redirect()->route('departments.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
        $departments = Department::findOrFail($id);

        //return show view
        return view('dashboard.departments.show', compact('departments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $partners = Profile::all();
       //find department
       $department = Department::findOrFail($id);
       //return edit view
       return view('dashboard.departments.edit', compact('partners','department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateDepartmentRequest $request, $id)
    {
       //find department
       $department=Department::where('id',$id)->first();
       //update department
       $this->departmentRepository->update($department,$request->only(
        'name',
        // 'partner_id',
       ));
       session()->flash('success', __('Department Updated'));
       return redirect()->route('departments.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       //find department
       $department=Department::findOrFail($id);
       //delete department
       $department->delete();
       //event delete department
       event(new DepartmentDeleted($department));
       session()->flash('success', __('Department Deleted'));
       return redirect()->route('departments.index');
    }
}

app/Http/Controllers/dashboard/EmployeeAdmdashController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Employee;
use App\Models\Profile;
use Redirect;


class EmployeeAdmdashController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $partners = Profile::where('credit_method','Employee Account')->get();
        return view('dashboard.employeesadmdash.indexwithoutemp', compact('partners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


}

app/Http/Controllers/dashboard/EmployeePartnerdashController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Employee;
use App\Models\Profile;
use App\Models\Department;
use App\Models\User;

class EmployeePartnerdashController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $provider=auth()->user()->id;
        $provider=User::findOrFail($provider);
        $provider=Profile::where('contact_email',$provider->email)->first();
        $employees = Employee::where('provider_id',$provider->id)->get();
        return view('dashboard.employees.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $provider=auth()->user()->id;
        $provider=User::findOrFail($provider);
        $provider=Profile::where('contact_email',$provider->email)->first();
        $departments = Department::all();
        $partners = Profile::all();
        
        return view('dashboard.employees.createpartnerdash', compact('provider','departments','partners'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $partner = $request->input('partner');
        $employees=Employee::where('provider_id',$partner)->get();
        // dd($partner);
       
        $partners = Profile::all();

        return view('dashboard.employees.index', compact('employees'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/employeesadmdash/index.blade.php
@extends('layouts.dashboard.base')
@section('pageTitle', 'Employees')

@section('content')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<style>
    .select2-container .select2-selection--single{
        height: 38px!important;
    }
    select2-container--default .select2-results__option--highlighted[aria-selected]{
        background-color: #00C4B3!important;
    }
    .select2-container--default .select2-results__option--highlighted[aria-selected], .select2-container--default .select2-results__option--highlighted[aria-selected]:hover{
        background-color: #00C4B3!important;
    }
</style>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Employees</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            {{ Breadcrumbs::render('employees.index') }}
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">All Employees</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    <form id="selectPartner" action="{{ route('search-export') }}" method="post">
                                        @csrf
                                        @method("POST")
                                        <div class="card-body">
                                            <div class="form-group">
                                                <label for="select_partner"> Select Partner</label>
                                                <select name="partner" class="form-control" id="select_partner" style='width: 200px'>
                                                    <option selected disabled>Please Select Partner</option>
                                                    @foreach ($partners as $partner)
                                                    <option value="{{$partner->id}}">{{$partner->partner_name}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" name="action" value="search" class="btn btn-primary"  style="background:#00C4B3!important;border-color:#00C4B3!important" >Search</button>
                                                <button type="submit" name="action" value="export_seclected_employees"class="btn btn-primary"  style="background:#00C4B3!important;border-color:#00C4B3!important" >Export Selected Employees</button>
                                                <button type="submit" name="action" value="export_all_employees"class="btn btn-primary"  style="background:#00C4B3!important;border-color:#00C4B3!important" >Export All Employees</button>
                                            </div>
                                            <script>
                                            $('#select_partner').select2({
                                                width: '100%',
                                                placeholder: "Select Partner",
                                                // allowClear: true,
                                            });
                                            </script>
                                        </div>
                                    </form>
                                </div>
                                <div class="container" style="overflow:auto">
                                    <table id="example1" class="table table-bordered table-striped"  style="overflow-x:scroll;width:10rem!important">
                                        <thead>
                                        <tr>
                                            <th>Full Name</th>
                                            <th>Work Title</th>
                                            <th>Department</th>
                                            <th>ID Number</th>
                                            <th>ID Front pic</th>
                                            <th>ID Back pic</th>
                                            <th>Bank Details</th>
                                            <th>Bank Name</th>
                                            <th>Transfer Customer Name</th>
                                            <th>AC</th>
                                            <th>IBAN</th>
                                            <th>Swift Code</th>
                                            <th>Mobile Number</th>
                                            <th>Email</th>
                                            <th>Credit Frequency</th>
                                            <th>Partner Name</th>
                                            <th>Qr Code</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($employees as $employee)
                                        <tr>
                                            <td>{{$employee->full_name}}</td>
                                            <td>{{$employee->work_title}}</td>
                                            <td>{{$employee->department->name}}</td>
                                            <td>{{$employee->id_number}}</td>
                                            <td><img style="width: 50px!important;" src="{{asset('storage/images/employees/id_front_pic/'.$employee->id_front_pic)}}" /></td>
                                            <td><img style="width: 50px!important;" src="{{asset('storage/images/employees/id_back_pic/'.$employee->id_back_pic)}}" /></td>
                                            <td>{{$employee->bank_details}}</td>
                                            <td>{{$employee->bank_name}}</td>
                                            <td>{{$employee->transfer_customer_name}}</td>
                                            <td>{{$employee->ac}}</td>
                                            <td>{{$employee->iban}}</td>
                                            <td>{{$employee->swift_code}}</td>
                                            <td>{{$employee->mobile_number}}</td>
                                            <td>{{$employee->email}}</td>
                                            <td>{{$employee->credit_frequency}}</td>
                                            <td>{{$employee->profile->partner_name}}</td>
                                            <td>
                                                <a href="{{asset('storage/images/'.$employee->qr_code)}}" download>
                                                <img style="width: 50px!important;" src="{{asset('storage/images/'.$employee->qr_code)}}" />
                                            </a>
                                            </td>
                                            <td>
                                                <div class="btn-group">
                                                    <a href="{{route('employees.edit',$employee->id)}}" type="button"
                                                    class="btn btn-default btn-flat">
                                                        <i class="fas fa-pen"></i>
                                                    </a>
                                                    <a href="{{route('employees.show',$employee->id)}}" type="button"
                                                    class="btn btn-default btn-flat">
                                                        <i class="fas fa-eye"></i>
                                                    </a>
                                                    <form method="post"
                                                        action="{{route('employees.destroy',$employee->id)}}">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-default btn-flat"><i
                                                                class="fas fa-trash"></i> </button>
                                                    </form>
                                                    <a href="{{route('update.password.get.admindash.employees',$employee->id)}}" type="button"
                                                    class="btn btn-default btn-flat">
                                                        <i class="fas fa-lock"></i>
                                                    </a>
                                                    @if($employee->is_active=='0')
                                                    <div class="btn-group" style="margin-left:5px">
                                                        <form method="post"
                                                            action="{{route('employee.admin.active',[$employee->id,$partner->id])}}">
                                                            @csrf
                                                            @method('POST')
                                                            <button type="submit" class="btn btn-primary"  style="background:#00C4B3!important;border-color:#00C4B3!important">Activate </button>
                                                        </form>
                                                    </div>
                                                    @endif
                                                    @if($employee->is_active=='1')
                                                    <div class="btn-group" style="margin-left:5px">
                                                        <form method="post"
                                                            action="{{route('employee.admin.deactive',[$employee->id,$partner->id])}}">
                                                            @csrf
                                                            @method('POST')
                                                            <button type="submit" class="btn btn-primary"  style="background:#00C4B3!important;border-color:#00C4B3!important">Deactivate</button>
                                                        </form>
                                                    </div>
                                                    @endif
                                                </div>
                                            </td>
                                        </tr>
                                        @endforeach
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>Full Name</th>
                                            <th>Work Title</th>
                                            <th>Department</th>
                                            <th>ID Number</th>
                                            <th>ID Front pic</th>
                                            <th>ID Back pic</th>
                                            <th>Bank Details</th>
                                            <th>Bank Name</th>
                                            <th>Transfer Customer Name</th>
                                            <th>AC</th>
                                            <th>IBAN</th>
                                            <th>Swift Code</th>
                                            <th>Mobile Number</th>
                                            <th>Email</th>
                                            <th>Credit Frequency</th>
                                            <th>Partner Name</th>
                                            <th>Qr Code</th>
                                            <th>Actions</th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

@endsection